#theme: jekyll-theme-slate
remote_theme: pmarsceill/just-the-docs

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase
